version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      # covered by k8s.io/cli-runtime
      - dependency-name: "k8s.io/api"
      - dependency-name: "k8s.io/apimachinery"
      - dependency-name: "k8s.io/client-go"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
